{
  "openapi": "3.0.3",
  "info": {
    "title": "simpay-api",
    "description": "",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.simpay.pl"
    }
  ],
  "tags": [
    {
      "name": "SMS"
    },
    {
      "name": "DirectBilling",
      "description": "# Sygnatura\n\n## Obliczanie sygnatury przy odbieraniu notyfikacji\n  Sygnature generujemy za pomocą zestawienia ze sobą wszystkich odebranych parametrów (oprócz signature) do API w kolejności z dostępnej powyżej tabli oddzielając je seperatorem | i dodając na końcu klucz dostępny w panelu klienta w usłudze.<br/>\n  Hashowanie musi odbyć się za pomocą sha256.<br/>\n  Przykład: <br/>\n  `dc261d4f-31ef-4728-bfd6-97bbe2a5ef0a|e14f8074|transaction_db_payed|11.07|13.67|5.00|http[...]"
    },
    {
      "name": "Payment",
      "x-displayName": "Płatności online",
      "description": "# Sygnatura\n\n## Obliczanie sygnatury przy odbieraniu notyfikacji\n  Sygnature generujemy za pomocą zestawienia ze sobą wszystkich odebranych parametrów (oprócz signature) do API w kolejności z dostępnej powyżej tabli oddzielając je seperatorem | i dodając na końcu klucz dostępny w panelu klienta w usłudze.<br/>\n  Hashowanie musi odbyć się za pomocą sha256.<br/>\n  Przykład: <br/>\n  `dc261d4f-31ef-4728-bfd6-97bbe2a5ef0a|e14f8074|transaction_paid|10|PLN|9.9|88643ada8857f2[...]"
    }
  ],
  "paths": {
    "/sms": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "sms.services"
            ]
          }
        ],
        "summary": "Lista usług",
        "operationId": "smsServiceList",
        "description": "Pobieranie listy dostępnych usług SMS na koncie",
        "tags": [
          "SMS"
        ]
      }
    },
    "/sms/{serviceId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "sms.services.show"
            ]
          }
        ],
        "summary": "Pobieranie informacji o usłudze",
        "operationId": "smsServiceShow",
        "tags": [
          "SMS"
        ]
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "sms.services.code"
            ]
          }
        ],
        "summary": "Weryfikacja poprawności kodu",
        "operationId": "smsServiceCheckCode",
        "tags": [
          "SMS"
        ]
      }
    },
    "/sms/{serviceId}/transactions": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "sms.services.transactions"
            ]
          }
        ],
        "summary": "Pobieranie listy transakcji",
        "operationId": "smsTransactionsList",
        "tags": [
          "SMS"
        ]
      }
    },
    "/sms/{serviceId}/transactions/{transactionId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "sms.services.transactions.show"
            ]
          }
        ],
        "summary": "Pobieranie informacji o transakcji",
        "operationId": "smsTransactionsShow",
        "tags": [
          "SMS"
        ]
      }
    },
    "/sms/{serviceId}/numbers": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "sms.services.numbers"
            ]
          }
        ],
        "summary": "Pobieranie informacji o numerach dla usługi",
        "operationId": "smsServiceNumbers",
        "tags": [
          "SMS"
        ]
      }
    },
    "/sms/{serviceId}/numbers/{number}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "sms.services.numbers.show"
            ]
          }
        ],
        "summary": "Pobieranie informacji o numerze dla usługi",
        "operationId": "smsServiceNumber",
        "tags": [
          "SMS"
        ]
      }
    },
    "/sms/numbers": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "sms.numbers"
            ]
          }
        ],
        "summary": "Pobieranie wszystkich dostępnych numerów",
        "operationId": "smsNumbers",
        "tags": [
          "SMS"
        ]
      }
    },
    "/sms/numbers/{number}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "sms.numbers.show"
            ]
          }
        ],
        "summary": "Pobieranie numeru",
        "operationId": "smsNumber",
        "tags": [
          "SMS"
        ]
      }
    },
    "/directbilling": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "directbilling.services"
            ]
          }
        ],
        "summary": "Pobieranie listy usług",
        "operationId": "directbillingGetServices",
        "description": "",
        "tags": [
          "DirectBilling"
        ]
      }
    },
    "/directbilling/{serviceId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "directbilling.services.show"
            ]
          }
        ],
        "summary": "Pobieranie informacji o usłudze",
        "operationId": "directbillingService",
        "description": "",
        "tags": [
          "DirectBilling"
        ]
      }
    },
    "/directbilling/{serviceId}/calculate": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "directbilling.services"
            ]
          }
        ],
        "summary": "Kalkulacja prowizji",
        "operationId": "directbillingServiceCalculate",
        "description": "",
        "tags": [
          "DirectBilling"
        ]
      }
    },
    "/directbilling/{serviceId}/transactions": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "directbilling.transactions"
            ]
          }
        ],
        "summary": "Pobieranie listy transakcji",
        "operationId": "directbillingTransactions",
        "description": "",
        "tags": [
          "DirectBilling"
        ]
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "directbilling.transactions.create"
            ]
          }
        ],
        "summary": "Generowanie transakcji",
        "operationId": "directbillingTransactionCreate",
        "description": "",
        "tags": [
          "DirectBilling"
        ]
      }
    },
    "/directbilling/{serviceId}/transactions/{transactionId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "directbilling.transactions.show"
            ]
          }
        ],
        "summary": "Pobieranie informacji o transakcji",
        "operationId": "directbillingTransaction",
        "description": "",
        "tags": [
          "DirectBilling"
        ]
      }
    },
    "/payment": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "payment.services"
            ]
          }
        ],
        "summary": "Pobieranie listy usług",
        "operationId": "paymentGetServices",
        "description": "",
        "tags": [
          "Payment"
        ]
      }
    },
    "/payment/{serviceId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "payment.service"
            ]
          }
        ],
        "summary": "Pobieranie szczegółów usługi",
        "operationId": "paymentGetService",
        "description": "",
        "tags": [
          "Payment"
        ]
      }
    },
    "/payment/{serviceId}/channels": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "payment.channels"
            ]
          }
        ],
        "summary": "Pobieranie listy kanałów dla usługi",
        "operationId": "paymentGetChannels",
        "description": "",
        "tags": [
          "Payment"
        ]
      }
    },
    "/payment/{serviceId}/transactions": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "payment.transactions"
            ]
          }
        ],
        "summary": "Pobieranie listy transakcji",
        "operationId": "paymentGetTransactions",
        "description": "",
        "tags": [
          "Payment"
        ]
      },
      "post": {
        "security": [
          {
            "bearerAuth": [
              "payment.transactions.create"
            ]
          }
        ],
        "summary": "Generowanie transakcji",
        "operationId": "paymentTransactionCreate",
        "description": "",
        "tags": [
          "Payment"
        ]
      }
    },
    "/payment/{serviceId}/transaction/{transactionId}": {
      "get": {
        "security": [
          {
            "bearerAuth": [
              "payment.transaction"
            ]
          }
        ],
        "summary": "Pobieranie szczegółów transakcji",
        "operationId": "paymentGetTransaction",
        "description": "",
        "tags": [
          "Payment"
        ]
      }
    }
  },
  "x-webhooks": {
    "directbillingTransactionNotification": {
      "post": {
        "summary": "Odbieranie informacji o transakcji",
        "description": "`POST`\n",
        "operationId": "directbillingTransactionNotification",
        "tags": [
          "DirectBilling"
        ]
      }
    },
    "paymentTransactionNotification": {
      "post": {
        "summary": "Odbieranie informacji o transakcji",
        "description": "`POST`\n",
        "operationId": "paymentTransactionNotification",
        "tags": [
          "Payment"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}